### ISSUE TITLE
Подгон размеров дизайна

### ISSUE THREAD

**Issue by Mr-Anonim-377** [Mr-Anonim-377/Tim-scientific-portal#14]
Подогнать размер дизайна под стандартный экранный размер 1920*1080 

1 стори поинт

**Comment by Mr-Anonim-377** [comment]
@sashafdtv  - ты закончил со своей частью задачи? Могу закрывать?

**Comment by sashafdtv** [comment]
@Mr-Anonim-377 да, все готово
